### PR TITLE
Add tests 

### PR DESCRIPTION
**Pull request by ellesmith88**
For issue #27

### CODE REVIEW

**Comment by ellesmith88** [comment]
@rsmith013 I haven't added any of the creating/deleting type tests that exist at https://github.com/stac-utils/stac-fastapi/tree/master/stac_fastapi/sqlalchemy/tests. It looked like you specifically didn't copy and paste them over when you put the placeholder tests in for me? is that right, or shall i add some?

**Comment by ellesmith88** [comment]
@rsmith013 @Mahir-Sparkess I've added tests for creating, deleting and updating collections and items. It looks like some of this isn't working as expected, I've put some comments on my tests with what I think is going on.

**Comment by Mahir-Sparkess** [comment]
Hi, I had a look at the test data which I think is where the problem arises. It isn't matching the stacspec for collections and items. So it doesn't recognize `_id` as the id when being [serialized](https://github.com/cedadev/stac-fastapi-elasticsearch/blob/80d1e92438e0988d1246160fbef96a003e9b6f8c/stac_fastapi/elasticsearch/models/serializers.py#L148) so I imagine elasticsearch generates a random one. 

There's a validator in [/stac_fastapi/elasticsearch/models/transactions_validator.py](https://github.com/cedadev/stac-fastapi-elasticsearch/blob/issue/27/test_coverage/stac_fastapi/elasticsearch/models/transactions_validator.py). If the request body passes the validator, the transaction should be safe pass. I hadn't implemented this since stac-pydantic was too strict of a validator, if only certain fields like link was optional.

My current issue with the transaction api is the lack of validation without having to define my own stac spec classes.

**Comment by ellesmith88** [comment]
@Mahir-Sparkess makes sense, they were in the elasticsearch format I think from before you had written the serialisers so the test data needs to be updated.

**Comment by Mahir-Sparkess** [comment]
@ellesmith88  I thinking splicing just the `['_source']` and adding an `['id']` key should work. Also I do not take into account pre-existing items/assets, and I realise my update method also takes in collection_id from the url when it should from the body. Tests 🙌 . I need to fix that on my end for update and already existing tests to work.

**Comment by ellesmith88** [comment]
@Mahir-Sparkess Great! I think `geometry` and `bbox` need to be changed in `items.json` in this branch as well. 

I'm not working until next Tuesday now so if you want to fix the test data and tests, feel free to make a PR to this branch (I think you can do that from a fork?). If not, I'll look at it next week 😄

**Comment by rsmith013** [comment]
@ellesmith88 @Mahir-Sparkess The other option is to write a small translation function to go from elasticsearch format to the STAC spec. 
I'll leave it to you to decide what is best. 
1. We could move to a model where the test data is ingested through the transaction API. I think that is how the [stac-fastapi](https://github.com/stac-utils/stac-fastapi/) repo does it. This would mean that all the tests fail if this doesn't work as expected as the data wouldn't be stored correctly.
2. Ingest the test data straight into elasticsearch (as is done now) and write a function to convert from the elasticsearch data into STAC specd data to test the endpoint. could you use the serialisers to do this, testing them at the same time?

**Pull request merged**
